config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post :add_item
    post :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  resources :users, only: [:new, :create]
  
  get 'register', to: 'users#new', as: 'register'
  post 'register', to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :require_admin

  def index
    @categories = Category.order(:name)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'Category created!'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<section class="admin-categories-index">
  <div class="container">
    <h1>Categories</h1>
    <%= link_to 'New Category', new_admin_category_path, class: 'btn btn-primary mb-3' %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/admin/categories/new.html.erb
<section class="admin-categories-new">
  <div class="container">
    <h1>New Category</h1>

    <%= form_with model: [:admin, @category], local: true do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mt-3">
        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</section>